import { describe, expect, it } from "vitest";
import { extractNuxtPayload, resolveNuxtPayload, sidearmAthleticsAdapter } from "./sidearm.js";
import { IngestionError } from "./types.js";

/**
 * Minimal devalue-style flattener — the inverse of resolveNuxtPayload.
 * Mirrors just enough of Nuxt's `__NUXT_DATA__` format (every value gets
 * its own array slot, containers reference children by index) to build
 * realistic HTML fixtures for these tests. Never shipped in the adapter
 * itself; the real payload is generated by Nuxt, not by us.
 */
function flatten(value: unknown): unknown[] {
  const arr: unknown[] = [];
  function put(v: unknown): number {
    const idx = arr.length;
    arr.push(null); // reserve the slot before recursing into children
    if (Array.isArray(v)) {
      arr[idx] = v.map((item) => put(item));
    } else if (v !== null && typeof v === "object") {
      const obj: Record<string, number> = {};
      for (const [k, val] of Object.entries(v as Record<string, unknown>)) obj[k] = put(val);
      arr[idx] = obj;
    } else {
      arr[idx] = v;
    }
    return idx;
  }
  put(value);
  return arr;
}

function htmlWithPayload(payload: unknown): string {
  return `<html><body><script id="__NUXT_DATA__" type="application/json">${JSON.stringify(flatten(payload))}</script></body></html>`;
}

const INDEX_PAYLOAD = {
  pinia: {
    sports: {
      sports: [
        { shortname: "wsoc", title: "Women's Soccer", non_sport: false, scheduleId: 3583 },
        { shortname: "general", title: "General", non_sport: true, scheduleId: null },
        { shortname: "mgolf", title: "Men's Golf", non_sport: false, scheduleId: null }, // no schedule to poll
      ],
    },
  },
};

const WSOC_SCHEDULE_PAYLOAD = {
  pinia: {
    schedule: {
      schedules: {
        "schedules-wsoc,": {
          games: [
            {
              id: 24657,
              date: "2026-08-12T19:00:00",
              time: "7:00 PM",
              location: "Boca Raton, Fla.",
              location_indicator: "H",
              at_vs: "vs",
              game_state_display: "SCHEDULED",
              game_center_link: "/game-center/24657",
              opponent: { title: "FIU", image: { fullpath: "https://example.com/fiu.png" } },
              result: {
                status: "T",
                team_score: "1",
                opponent_score: "1",
                boxscore: { url: "/boxscore.aspx?id=24657" },
              },
            },
            {
              id: 24658,
              date: "2026-08-16T19:00:00",
              time: "7:00 PM",
              location: "Boca Raton, Fla.",
              location_indicator: "H",
              at_vs: "vs",
              game_state_display: "SCHEDULED",
              game_center_link: "/game-center/24658",
              opponent: { title: "Miami", image: { fullpath: "https://example.com/miami.png" } },
              result: null,
            },
            {
              // multi-team tournament entry — no single opponent, so no logo to source an image from
              id: 24700,
              date: "2026-09-20T00:00:00",
              time: "TBA",
              location: "Gainesville, Fla.",
              location_indicator: "N",
              at_vs: "vs",
              game_state_display: "SCHEDULED",
              game_center_link: "/game-center/24700",
              opponent: { title: "Gator Invitational" },
              result: null,
            },
          ],
        },
      },
    },
  },
};

describe("resolveNuxtPayload", () => {
  it("round-trips a flattened object through extractNuxtPayload", () => {
    const html = htmlWithPayload(WSOC_SCHEDULE_PAYLOAD);
    expect(extractNuxtPayload(html)).toEqual(WSOC_SCHEDULE_PAYLOAD);
  });

  it("unwraps Reactive/ShallowReactive wrapper tags", () => {
    const arr = [["Reactive", 1], { a: 2 }, "hello"];
    expect(resolveNuxtPayload(arr, 0)).toEqual({ a: "hello" });
  });

  it("resolves a Set tag", () => {
    const arr = [["Set", 1, 2], "x", "y"];
    expect(resolveNuxtPayload(arr, 0)).toEqual(new Set(["x", "y"]));
  });

  it("resolves a Map tag", () => {
    const arr = [["Map", 1, 2], "key", "value"];
    expect(resolveNuxtPayload(arr, 0)).toEqual(new Map([["key", "value"]]));
  });

  it("returns null when the page has no __NUXT_DATA__ script", () => {
    expect(extractNuxtPayload("<html><body>no payload here</body></html>")).toBeNull();
  });
});

describe("sidearmAthleticsAdapter", () => {
  const BASE_URL = "https://example-athletics.com/calendar";

  function fakeFetch(routes: Record<string, string>): typeof fetch {
    return (async (url: string) => {
      const html = routes[url];
      return html ? new Response(html, { status: 200 }) : new Response("", { status: 404 });
    }) as unknown as typeof fetch;
  }

  it("discovers sports on the index page, then fetches each sport's schedule", async () => {
    const items = await sidearmAthleticsAdapter.fetchNew({
      source: { id: "src-1", url: BASE_URL, instagramHandle: null, metadata: {} },
      lastSuccessfulCheckAt: null,
      fetchImpl: fakeFetch({
        [BASE_URL]: htmlWithPayload(INDEX_PAYLOAD),
        "https://example-athletics.com/sports/wsoc/schedule": htmlWithPayload(WSOC_SCHEDULE_PAYLOAD),
      }),
    });

    // "general" is non_sport, "mgolf" has no scheduleId — only wsoc's three games should surface
    expect(items).toHaveLength(3);
    const item = items[0]!;
    expect(item.externalId).toBe("sidearm-game-24657");
    expect(item.sourceUrl).toBe("https://example-athletics.com/game-center/24657");
    expect(item.rawText).toContain("Women's Soccer vs FIU");
    expect(item.rawText).toContain("Start: 2026-08-12T19:00:00");
    expect(item.rawText).toContain("Location: Boca Raton, Fla.");
    expect(item.rawText).toContain("Result: Final 1-1");
    expect(item.mediaUrl).toBe("https://example.com/fiu.png");
    expect(item.publishedAt).toBeNull();
    expect(item.rawMetadata).toMatchObject({
      sport: "Women's Soccer",
      opponent: "FIU",
      locationIndicator: "H",
      gameState: "SCHEDULED",
    });

    // opponent logo when there's a single named opponent; null (not a
    // guessed/generic image) for a multi-team entry with no one opponent to
    // source a crest from — packages/render supplies a category-tinted
    // placeholder graphic downstream for exactly that null case.
    expect(items[0]!.mediaUrl).toBe("https://example.com/fiu.png");
    expect(items[1]!.mediaUrl).toBe("https://example.com/miami.png");
    expect(items[2]!.mediaUrl).toBeNull();
  });

  it("skips a sport whose schedule page fails to fetch, without failing the whole run", async () => {
    const items = await sidearmAthleticsAdapter.fetchNew({
      source: { id: "src-1", url: BASE_URL, instagramHandle: null, metadata: {} },
      lastSuccessfulCheckAt: null,
      // wsoc schedule route deliberately omitted -> 404
      fetchImpl: fakeFetch({ [BASE_URL]: htmlWithPayload(INDEX_PAYLOAD) }),
    });
    expect(items).toEqual([]);
  });

  it("throws when the source has no URL configured", async () => {
    await expect(
      sidearmAthleticsAdapter.fetchNew({
        source: { id: "src-1", url: null, instagramHandle: null, metadata: {} },
        lastSuccessfulCheckAt: null,
      }),
    ).rejects.toBeInstanceOf(IngestionError);
  });

  it("throws when the index page has no discoverable sports", async () => {
    const emptyPayload = { pinia: { sports: { sports: [] } } };
    await expect(
      sidearmAthleticsAdapter.fetchNew({
        source: { id: "src-1", url: BASE_URL, instagramHandle: null, metadata: {} },
        lastSuccessfulCheckAt: null,
        fetchImpl: fakeFetch({ [BASE_URL]: htmlWithPayload(emptyPayload) }),
      }),
    ).rejects.toBeInstanceOf(IngestionError);
  });

  it("respects maxItems across combined sports", async () => {
    const items = await sidearmAthleticsAdapter.fetchNew({
      source: { id: "src-1", url: BASE_URL, instagramHandle: null, metadata: {} },
      lastSuccessfulCheckAt: null,
      maxItems: 1,
      fetchImpl: fakeFetch({
        [BASE_URL]: htmlWithPayload(INDEX_PAYLOAD),
        "https://example-athletics.com/sports/wsoc/schedule": htmlWithPayload(WSOC_SCHEDULE_PAYLOAD),
      }),
    });
    expect(items).toHaveLength(1);
  });
});
