// Build-time only (never runs in production/deployed code). Extracts every
// printable-ASCII glyph's raw outline (in font units, unscaled/unpositioned)
// from each bundled .ttf and writes it as a TypeScript MODULE with the JSON
// embedded as a base64 string — not as a loose .json data file. That's
// deliberate: the deployed function bundle is produced by file-tracing the
// compiled dist, and this session proved the hard way that any runtime
// file read (fonts via fontconfig, then .ttf files, then .json files) is a
// deployment liability. Embedded in a module, the glyph data is ordinary
// imported code: tsc emits it into dist, the bundler traces it like any
// import, and there is nothing left to go missing at runtime.
//
// Re-run (`pnpm generate-glyphs`) only if the bundled .ttf files change.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ASSETS_DIR = join(__dirname, "..", "assets");
const OUT_DIR = join(__dirname, "..", "src", "glyph-data");

const FONTS = [
  { file: "Anton-Regular.ttf", out: "anton.ts" },
  { file: "Archivo-Bold.ttf", out: "archivo-bold.ts" },
  { file: "Archivo-Regular.ttf", out: "archivo-regular.ts" },
];

// Printable ASCII, space through tilde, plus the handful of non-ASCII marks
// actually used un-normalized by the renderer. "•" (U+2022) is the one that
// bit us: metaParts.join("   •   ") in svgTemplate.ts uses it directly
// rather than through TYPOGRAPHY_NORMALIZE (unlike –/—/… which do map to
// ASCII there), so without its glyph extracted, sanitizeForFont silently
// dropped every bullet the layout code emitted — no error, just an
// increasingly wide gap where the separator should have been.
const CHARS = [
  ...Array.from({ length: 0x7e - 0x20 + 1 }, (_, i) => String.fromCharCode(0x20 + i)),
  "•", // •
];

mkdirSync(OUT_DIR, { recursive: true });

for (const { file, out } of FONTS) {
  const buffer = readFileSync(join(ASSETS_DIR, file));
  const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  const font = opentype.parse(arrayBuffer);

  const glyphs = {};
  for (const char of CHARS) {
    const glyph = font.charToGlyph(char);
    glyphs[char] = {
      advanceWidth: glyph.advanceWidth ?? 0,
      commands: glyph.path.commands,
    };
  }

  const payload = Buffer.from(JSON.stringify({ unitsPerEm: font.unitsPerEm, glyphs }), "utf8").toString("base64");
  const module = `// AUTO-GENERATED by scripts/extract-glyphs.mjs from ${file} — do not edit by hand.
// Base64-embedded (rather than a big object literal or template string) so
// the payload is immune to escaping issues and cheap for tsc to check.
import type { GlyphFont } from "../glyphTypes.js";

export const font: GlyphFont = JSON.parse(Buffer.from(
  "${payload}",
  "base64",
).toString("utf8")) as GlyphFont;
`;
  writeFileSync(join(OUT_DIR, out), module);
  console.log(`Wrote ${out}: ${Object.keys(glyphs).length} glyphs, unitsPerEm=${font.unitsPerEm}, base64Bytes=${payload.length}`);
}
